version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: biometriq
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "25432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d biometriq"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/static:/app/static
    environment:
      DATABASE_URL: postgresql://admin:password@postgres:5432/biometriq
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
