"""Create rockets table

Revision ID: b34d73a9716b
Revises: 
Create Date: 2025-08-20 15:42:09.207095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b34d73a9716b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rockets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('mission', sa.String(length=500), nullable=True),
    sa.Column('attempted_landings', sa.Integer(), nullable=True),
    sa.Column('successful_landings', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rockets')
    # ### end Alembic commands ###
